In [58]:
import pandas as pd
import numpy as np

In [59]:
matches_info_df = pd.read_csv("matches_info_df.csv", index_col=0)
matches_info_df

,B365H,home_team_name,B365D,away_team_name,B365A,Pre-Match PPG (Home),Pre-Match PPG (Away),home_team_goal_count,away_team_goal_count,home_team_goal_count_half_time,away_team_goal_count_half_time,home_team_goal_timings,away_team_goal_timings,home_team_shots,home_team_shots_on_target,away_team_shots,away_team_shots_on_target,season_part,day_or_night
0,1.57,Manchester United,3.90,Leicester City,7.50,0.00,0.00,2,1,1,0,"3,83",90'2,8,7,8,5,first,Night
1,3.90,Newcastle United,3.50,Tottenham Hotspur,2.04,0.00,0.00,1,2,1,2,11,"8,18",11,3,13,6,first,Day
2,1.90,AFC Bournemouth,3.60,Cardiff City,4.50,0.00,0.00,2,0,1,0,"24,90'1",NaN,11,5,7,2,first,Day
3,2.50,Fulham,3.40,Crystal Palace,3.00,0.00,0.00,0,2,0,1,NaN,"41,79",11,7,11,11,first,Day
4,6.50,Huddersfield Town,4.00,Chelsea,1.61,0.00,0.00,0,3,0,2,NaN,"34,45,80",6,2,8,5,first,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,1.30,Liverpool,6.00,Wolverhampton Wanderers,11.00,2.78,1.28,2,0,1,0,"17,81",NaN,11,6,7,3,last,Day
376,1.28,Manchester United,6.50,Cardiff City,11.00,2.00,0.61,0,2,0,1,NaN,"23,54",21,11,11,5,last,Day
377,1.44,Southampton,4.75,Huddersfield Town,8.50,1.22,0.33,1,1,1,0,41,55,7,4,8,4,last,Day
378,2.20,Tottenham Hotspur,3.50,Everton,3.50,2.06,1.06,2,2,1,0,"3,75","69,72",9,4,13,10,last,Day
379,2.25,Watford,3.75,West Ham United,3.20,1.50,1.00,1,4,0,2,46,"15,39,71,78",11,9,15,10,last,Day

In [64]:
porcentagem = 0.5
num_linhas = len(matches_info_df)
num_valores_para_sujar = int(num_linhas * porcentagem)

coluna = 'home_team_shots'

indices_para_sujar = np.random.choice(matches_info_df.index, num_valores_para_sujar, replace=False)

matches_info_df.loc[indices_para_sujar, coluna] = np.nan

num_nans = matches_info_df['home_team_shots'].isna().sum()

matches_info_df.head(50)

,B365H,home_team_name,B365D,away_team_name,B365A,Pre-Match PPG (Home),Pre-Match PPG (Away),home_team_goal_count,away_team_goal_count,home_team_goal_count_half_time,away_team_goal_count_half_time,home_team_goal_timings,away_team_goal_timings,home_team_shots,home_team_shots_on_target,away_team_shots,away_team_shots_on_target,season_part,day_or_night
0,1.57,Manchester United,3.90,Leicester City,7.50,0.0,0.0,2,1,1,0,"3,83",90'2,NaN,7,8,5,first,Night
1,3.90,Newcastle United,3.50,Tottenham Hotspur,2.04,0.0,0.0,1,2,1,2,11,"8,18",NaN,3,13,6,first,Day
2,1.90,AFC Bournemouth,3.60,Cardiff City,4.50,0.0,0.0,2,0,1,0,"24,90'1",NaN,NaN,5,7,2,first,Day
3,2.50,Fulham,3.40,Crystal Palace,3.00,0.0,0.0,0,2,0,1,NaN,"41,79",NaN,7,11,11,first,Day
4,6.50,Huddersfield Town,4.00,Chelsea,1.61,0.0,0.0,0,3,0,2,NaN,"34,45,80",NaN,2,8,5,first,Day
5,2.37,Watford,3.20,Brighton & Hove Albion,3.40,0.0,0.0,2,0,1,0,"35,54",NaN,NaN,6,6,0,first,Day
6,2.37,Wolverhampton Wanderers,3.30,Everton,3.30,0.0,0.0,2,2,1,1,"44,80","17,67",NaN,5,9,6,first,Day
7,1.25,Liverpool,6.50,West Ham United,14.00,0.0,0.0,4,0,2,0,"19,45'2,53,88",NaN,NaN,9,5,3,first,Day
8,1.85,Southampton,3.50,Burnley,5.00,0.0,0.0,0,0,0,0,NaN,NaN,NaN,4,13,7,first,Day
9,4.00,Arsenal,3.80,Manchester City,1.95,0.0,0.0,0,2,0,1,NaN,"14,64",NaN,4,14,9,first,Day
10,3.25,Cardiff City,3.10,Newcastle United,2.54,0.0,0.0,0,0,0,0,NaN,NaN,NaN,2,8,7,first,Day
11,1.90,Everton,3.50,Southampton,4.75,0.0,0.0,2,1,2,0,"15,31",54,NaN,8,11,5,first,Day
12,2.04,Leicester City,3.50,Wolverhampton Wanderers,3.90,0.0,0.0,2,0,2,0,"29,45",NaN,NaN,3,11,4,first,Day
13,1.28,Tottenham Hotspur,6.00,Fulham,12.00,0.0,0.0,3,1,1,0,"43,74,77",52,NaN,12,9,4,first,Day
14,2.10,West Ham United,3.60,AFC Bournemouth,3.70,0.0,0.0,1,2,1,0,33,"60,66",NaN,6,9,6,first,Day
15,1.80,Chelsea,4.00,Arsenal,4.50,0.0,0.0,3,2,2,2,"9,20,81","37,41",NaN,12,13,7,first,Day
16,2.45,Burnley,3.10,Watford,3.40,0.0,0.0,1,3,1,1,6,"3,48,51",NaN,4,7,7,first,Day
17,1.10,Manchester City,13.00,Huddersfield Town,26.00,0.0,0.0,6,1,3,1,"25,31,35,48,75,84",43,NaN,15,4,2,first,Day
18,5.50,Brighton & Hove Albion,3.60,Manchester United,1.75,0.0,0.0,3,2,3,1,"25,27,44","34,90'5",NaN,4,8,4,first,Day
19,7.00,Crystal Palace,5.00,Liverpool,1.44,0.0,0.0,0,2,0,1,NaN,"45,90'3",NaN,3,11,7,first,Night
20,11.00,Wolverhampton Wanderers,6.50,Manchester City,1.28,1.0,3.0,1,1,0,0,57,69,NaN,3,13,7,first,Day
21,2.62,AFC Bournemouth,3.60,Everton,2.75,3.0,1.0,2,2,0,0,"75,79","56,66",16.0,6,9,4,first,Day
22,1.36,Arsenal,5.50,West Ham United,9.00,0.0,0.0,3,1,1,1,"30,70,90'2",25,NaN,11,11,6,first,Day
23,2.37,Huddersfield Town,3.00,Cardiff City,3.70,0.0,0.0,0,0,0,0,NaN,NaN,NaN,2,11,5,first,Day
24,2.45,Southampton,3.20,Leicester City,3.25,1.0,0.0,1,2,0,0,52,"56,90'2",NaN,6,9,6,first,Day
25,1.16,Liverpool,8.50,Brighton & Hove Albion,19.00,3.0,0.0,1,0,1,0,23,NaN,NaN,9,5,3,first,Day
26,2.60,Watford,3.25,Crystal Palace,3.00,3.0,3.0,2,1,0,0,"53,71",78,NaN,6,9,4,first,Day
27,2.00,Fulham,3.40,Burnley,4.33,0.0,1.0,4,2,3,2,"4,36,38,83","10,41",NaN,13,8,3,first,Day
28,5.75,Newcastle United,4.00,Chelsea,1.66,0.0,3.0,1,2,0,0,83,"76,87",NaN,3,11,4,first,Day
29,2.62,Manchester United,3.30,Tottenham Hotspur,2.90,3.0,3.0,0,3,0,0,NaN,"50,52,84",18.0,6,8,6,first,Night
30,7.50,Leicester City,5.00,Liverpool,1.44,3.0,3.0,1,2,0,2,63,"10,45",NaN,6,9,5,first,Day
31,2.30,Brighton & Hove Albion,3.40,Fulham,3.40,3.0,0.0,2,2,0,1,"67,84","43,62",NaN,6,9,6,first,Day
32,1.30,Chelsea,6.00,AFC Bournemouth,11.00,3.0,3.0,2,0,0,0,"72,85",NaN,13.0,7,8,2,first,Day
33,2.00,Crystal Palace,3.50,Southampton,4.20,0.0,0.0,0,2,0,0,NaN,"47,90'2",NaN,7,13,7,first,Day
34,1.53,Everton,4.20,Huddersfield Town,7.50,3.0,0.0,1,1,1,1,36,34,NaN,2,8,7,first,Day
35,2.60,West Ham United,3.40,Wolverhampton Wanderers,2.87,0.0,0.0,0,1,0,0,NaN,90'3,NaN,4,14,7,first,Day
36,1.11,Manchester City,11.00,Newcastle United,26.00,3.0,1.0,2,1,1,1,"8,52",30,NaN,9,4,3,first,Day
37,6.50,Cardiff City,4.33,Arsenal,1.57,1.0,0.0,2,3,1,1,"45'2,70","11,62,81",NaN,4,16,12,first,Day
38,6.00,Burnley,3.75,Manchester United,1.70,0.0,0.0,0,2,0,2,NaN,"27,44",NaN,3,16,10,first,Day
39,5.50,Watford,4.20,Tottenham Hotspur,1.64,3.0,3.0,2,1,0,0,"69,76",53,NaN,4,10,3,first,Day
40,3.00,Tottenham Hotspur,3.60,Liverpool,2.40,3.0,3.0,1,2,0,1,90'3,"39,54",NaN,4,16,11,first,Day
41,2.45,AFC Bournemouth,3.50,Leicester City,3.00,2.0,1.5,4,2,3,0,"19,37,41,81","88,89",NaN,6,13,9,first,Day
42,1.18,Chelsea,8.00,Cardiff City,19.00,3.0,0.5,4,1,2,1,"37,43,80,83",16,NaN,8,7,3,first,Day
43,3.30,Huddersfield Town,3.10,Crystal Palace,2.50,0.5,1.5,0,1,0,1,NaN,38,NaN,3,5,3,first,Day
44,1.12,Manchester City,10.00,Fulham,26.00,3.0,0.5,3,0,2,0,"2,21,47",NaN,NaN,10,9,4,first,Day
45,4.20,Newcastle United,3.80,Arsenal,1.90,0.0,1.5,1,2,0,0,90'1,"49,58",NaN,3,8,3,first,Day
46,4.33,Watford,3.60,Manchester United,1.95,3.0,1.5,1,2,0,2,65,"35,38",NaN,6,8,7,first,Day
47,1.75,Wolverhampton Wanderers,3.60,Burnley,5.75,1.0,0.5,1,0,0,0,61,NaN,NaN,8,8,3,first,Day
48,2.00,Everton,3.75,West Ham United,3.90,2.0,0.0,1,3,1,2,45'2,"11,31,61",NaN,5,7,5,first,Day
49,2.10,Southampton,3.40,Brighton & Hove Albion,3.90,0.5,0.0,2,2,1,0,"35,65","67,90",NaN,6,10,5,first,Night